'use client';

import { FormEvent, useState } from 'react';
import { ArrowForwardRounded, CheckRounded, CloseRounded } from '@mui/icons-material';
import { Dialog, DialogContent, IconButton, LinearProgress } from '@mui/material';
import ReactMarkdown from 'react-markdown';
import remarkGfm from 'remark-gfm';
import type { LearnerProfile, LearningMaterial, LearningWorkspace, PublicPlacementAssessment } from '../../shared/contracts';

export type GoalInput = { title: string; motivation: string; targetOutcome: string; background: string; preferences: string };

export function GoalDialog({ open, busy, profile, onClose, onSubmit }: { open: boolean; busy: boolean; profile: LearnerProfile; onClose: () => void; onSubmit: (input: GoalInput) => Promise<void> }) {
  const [form, setForm] = useState<GoalInput>({ title: '', motivation: '', targetOutcome: '', background: profile.background, preferences: profile.preferences });
  const submit = async (event: FormEvent) => { event.preventDefault(); await onSubmit(form); };
  return <Dialog open={open} onClose={busy ? undefined : onClose} maxWidth="sm" fullWidth slotProps={{ paper: { className: 'studio-dialog' } }}><IconButton className="dialog-close" disabled={busy} onClick={onClose}><CloseRounded /></IconButton><DialogContent><span className="dialog-kicker">YOUR LEARNING PROFILE</span><h2>Shape your learning goal</h2><p>This gives AdaptLearn enough context to personalize your experience. No materials are created until you ask.</p><form className="goal-form" onSubmit={submit}><label>What do you want to learn?<input required minLength={2} value={form.title} onChange={(event) => setForm({ ...form, title: event.target.value })} placeholder="e.g. Lead clearer project meetings" /></label><label>Why does it matter?<textarea value={form.motivation} onChange={(event) => setForm({ ...form, motivation: event.target.value })} placeholder="The situation or motivation behind this goal" /></label><label>What would success look like?<textarea value={form.targetOutcome} onChange={(event) => setForm({ ...form, targetOutcome: event.target.value })} placeholder="A practical outcome you want to reach" /></label><div className="form-pair"><label>Your current background<textarea value={form.background} onChange={(event) => setForm({ ...form, background: event.target.value })} placeholder="What you already know" /></label><label>How you prefer to learn<textarea value={form.preferences} onChange={(event) => setForm({ ...form, preferences: event.target.value })} placeholder="Examples, practice, conversation…" /></label></div><button className="dialog-primary" disabled={busy}>{busy ? 'Saving…' : 'Save goal'} <ArrowForwardRounded /></button></form></DialogContent></Dialog>;
}

export function MemoryDialog({ open, busy, workspace, onClose, onSave }: { open: boolean; busy: boolean; workspace: LearningWorkspace; onClose: () => void; onSave: (profile: LearnerProfile) => Promise<void> }) {
  const goal = workspace.goals.find((item) => item.status === 'active');
  const [form, setForm] = useState<LearnerProfile>(workspace.profile);
  const submit = async (event: FormEvent) => { event.preventDefault(); await onSave(form); };
  return <Dialog open={open} onClose={busy ? undefined : onClose} maxWidth="sm" fullWidth slotProps={{ paper: { className: 'studio-dialog' } }}><IconButton className="dialog-close" disabled={busy} onClick={onClose}><CloseRounded /></IconButton><DialogContent><span className="dialog-kicker">PROFILE &amp; PROGRESS</span><h2>Edit your learner profile</h2><p>These details personalize future lessons and remain in your local workspace.</p><form className="goal-form profile-form" onSubmit={submit}><label>Display name<input required maxLength={100} value={form.displayName} onChange={(event) => setForm({ ...form, displayName: event.target.value })} /></label><label>Your current background<textarea maxLength={1500} value={form.background} onChange={(event) => setForm({ ...form, background: event.target.value })} placeholder="Experience, role, or what you already know" /></label><label>How you prefer to learn<textarea maxLength={1000} value={form.preferences} onChange={(event) => setForm({ ...form, preferences: event.target.value })} placeholder="Examples, guided practice, conversation…" /></label><button className="dialog-primary" disabled={busy}>{busy ? 'Saving…' : 'Save profile'} <CheckRounded /></button></form><div className="memory-grid compact"><div><span>Current level</span><strong>{workspace.progress.level}</strong></div><div><span>XP evidence</span><strong>{workspace.progress.xp} XP</strong></div><div className="wide"><span>Active goal</span><strong>{goal?.title ?? 'No goal yet'}</strong></div><div><span>Assessments</span><strong>{workspace.progress.completedAssessments}</strong></div><div><span>Documents</span><strong>{workspace.documents.length}</strong></div></div></DialogContent></Dialog>;
}

export function MaterialDialog({ material, onClose }: { material?: LearningMaterial; onClose: () => void }) {
  const label = material?.kind === 'practice-lab' ? 'PRACTICE ACTIVITY' : 'SOURCED LESSON';
  return <Dialog open={Boolean(material)} onClose={onClose} maxWidth="md" fullWidth slotProps={{ paper: { className: 'studio-dialog material-dialog' } }}><IconButton className="dialog-close" onClick={onClose}><CloseRounded /></IconButton>{material && <DialogContent><span className="dialog-kicker">{label}</span><h2>{material.title}</h2><p>{material.summary}</p><div className="material-sections">{material.sections.map((section, index) => <section key={`${section.title}-${index}`}><span>{String(index + 1).padStart(2, '0')}</span><div><h3>{section.title}</h3><div className="lesson-content"><ReactMarkdown remarkPlugins={[remarkGfm]} components={{ a: ({ href, title, children }) => <a href={href} title={title} target="_blank" rel="noreferrer">{children}</a> }}>{section.content}</ReactMarkdown></div>{section.activities && section.activities.length > 0 && <div className="lesson-activities"><strong>Try it</strong><ul>{section.activities.map((activity) => <li key={activity}>{activity}</li>)}</ul></div>}</div></section>)}</div>{material.sources && material.sources.length > 0 && <section className="lesson-sources"><span>SOURCES USED</span><h3>Where this lesson came from</h3><div>{material.sources.map((source, index) => <article key={`${source.title}-${index}`}><small>{source.origin === 'uploaded-document' ? 'YOUR UPLOADED DOCUMENT' : 'PUBLIC WEB'}</small>{source.url ? <a href={source.url} target="_blank" rel="noreferrer">{source.title} ↗</a> : <strong>{source.title}</strong>}</article>)}</div></section>}</DialogContent>}</Dialog>;
}

export function PlacementDialog({ assessment, busy, result, onClose, onSubmit }: { assessment?: PublicPlacementAssessment; busy: boolean; result?: { score: number; level: string; xpAwarded: number; badgeAwarded?: string }; onClose: () => void; onSubmit: (answers: number[]) => Promise<void> }) {
  const [answers, setAnswers] = useState<number[]>([]);
  if (!assessment) return null;
  const answered = answers.filter((value) => value >= 0).length;
  const choose = (questionIndex: number, optionIndex: number) => { const next = [...answers]; next[questionIndex] = optionIndex; setAnswers(next); };
  return <Dialog open onClose={busy ? undefined : onClose} maxWidth="md" fullWidth slotProps={{ paper: { className: 'studio-dialog placement-dialog' } }}><IconButton className="dialog-close" disabled={busy} onClick={onClose}><CloseRounded /></IconButton><DialogContent><span className="dialog-kicker">PLACEMENT CHECK</span>{result ? <div className="placement-result"><span><CheckRounded /></span><h2>{result.level}</h2><p>{result.score}% demonstrated · +{result.xpAwarded} XP</p>{result.badgeAwarded && <strong>Badge earned: {result.badgeAwarded}</strong>}<button className="dialog-primary" onClick={onClose}>Return to workspace</button></div> : <><h2>{assessment.title}</h2><p>This measures a starting point; it does not teach or penalize skipped knowledge.</p><LinearProgress variant="determinate" value={(answered / assessment.questions.length) * 100} /><div className="placement-questions">{assessment.questions.map((question, questionIndex) => <section key={question.id}><span>QUESTION {questionIndex + 1}</span><h3>{question.prompt}</h3><div>{question.options.map((option, optionIndex) => <button className={answers[questionIndex] === optionIndex ? 'selected' : ''} onClick={() => choose(questionIndex, optionIndex)} key={option}>{option}</button>)}</div></section>)}</div><button className="dialog-primary submit-placement" disabled={busy || answered !== assessment.questions.length} onClick={() => onSubmit(answers)}>{busy ? 'Scoring…' : 'See my result'} <ArrowForwardRounded /></button></>}</DialogContent></Dialog>;
}
